[package]
name = "zeblang_wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
zeblang = { git = "https://github.com/zeb33n/zeblang.git", branch="master" }
